Ext.define('SSJT.model.Report', {
    extend: 'SSJT.model.Base',

    fields: [
        {
            name:'A',
            allowNull:true
        },
        {
            name:'B',
            allowNull:true
        },
        {
            name:'C',
            allowNull:true
        },
        {
            name:'D',
            allowNull:true
        },
        {
            name:'E',
            allowNull:true
        },
        {
            name:'F',
            allowNull:true
        },
        {
            name:'G',
            allowNull:true
        },
        {
            name:'H',
            allowNull:true
        },
        {
            name:'I',
            allowNull:true
        },
        {
            name:'J',
            allowNull:true
        },
        {
            name:'K',
            allowNull:true
        },
        {
            name:'L',
            allowNull:true
        },
        {
            name:'M',
            allowNull:true
        },
        {
            name:'N',
            allowNull:true
        },
        {
            name:'O',
            allowNull:true
        },
        {
            name:'P',
            allowNull:true
        },
        {
            name:'Q',
            allowNull:true
        },
        {
            name:'R',
            allowNull:true
        },
        {
            name:'S',
            allowNull:true
        },
        {
            name:'T',
            allowNull:true
        },
        {
            name:'U',
            allowNull:true
        },
        {
            name:'V',
            allowNull:true
        },
        {
            name:'W',
            allowNull:true
        },
        {
            name:'X',
            allowNull:true
        },
        {
            name:'Y',
            allowNull:true
        },
        {
            name:'Z',
            allowNull:true
        }
    ]
});

